import assert from 'node:assert/strict';
import { isCorrect } from './app/scoring.ts';
assert.equal(isCorrect(['B'], ['B']), true);
assert.equal(isCorrect(['A'], ['B']), false);
assert.equal(isCorrect(['C','A'], ['A','C']), true);
assert.equal(isCorrect(['A'], ['A','C']), false);
assert.equal(isCorrect(['A','B','C'], ['A','C']), false);
assert.equal(isCorrect(['A','A'], ['A','C']), false);
assert.equal(isCorrect(['正确'], ['错误']), false);
assert.equal(isCorrect([], ['正确']), false);
console.log('Scoring checks passed.');
